spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: user
    password: pass
  h2:
    console.enabled: true
  flyway:
    baseline-on-migrate: true
    baseline-description: baseline
    baseline-version: 0
    table: example_schema_version
    locations: classpath:com.logix.flywaydemo.migrations,classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect