spring:
  datasource:
    url: jdbc:h2:file:/Users/NinjaLogix/Dev/Code/flyway-demo
    driver-class-name: org.h2.Driver
    username: user
    password: pass
  h2:
    console.enabled: true
  flyway:
    baseline-on-migrate: true
    baseline-description: baseline
    baseline-version: 0
    table: example_schema_version
    locations: classpath:db/migration # - Manual setting for sql migrations. This is also the default path for sql migrations
    #locations: classpath:com.logix.flywaydemo.migrations # - Manual setting for Java migrations
    #locations: classpath:com.logix.flywaydemo.migrations,classpath:db/migration # - Mix and match for various migrations
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none